export const pacman = {
  'header': {
    'type': 'MThd',
    'length': 6,
    'format': 1,
    'tracks': 3,
    'division': 96,
    'next': 14,
  },
  'tracks': [
    {
      'events': [
        {
          'type': 3,
          'data': 'Pac-Man - Level intro',
          'next': 100,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 10,
            'value': 64,
            'channel': 1,
          },
          'next': 104,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 7,
            'value': 127,
            'channel': 1,
          },
          'next': 108,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 14,
          'b1': 0,
          'b2': 0,
          'next': 112,
          'channel': 1,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 101,
            'value': 0,
            'channel': 1,
          },
          'next': 116,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 100,
            'value': 0,
            'channel': 1,
          },
          'next': 120,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 6,
            'value': 12,
            'channel': 1,
          },
          'next': 124,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 10,
            'value': 64,
            'channel': 1,
          },
          'next': 128,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 7,
            'value': 127,
            'channel': 1,
          },
          'next': 132,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 14,
          'b1': 0,
          'b2': 0,
          'next': 136,
          'channel': 1,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 12,
          'data': {
            'value': 80,
            'channel': 1,
          },
          'next': 139,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 101,
            'value': 0,
            'channel': 1,
          },
          'next': 143,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 100,
            'value': 0,
            'channel': 1,
          },
          'next': 147,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 6,
            'value': 12,
            'channel': 1,
          },
          'next': 151,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 10,
            'value': 64,
            'channel': 1,
          },
          'next': 155,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 7,
            'value': 127,
            'channel': 1,
          },
          'next': 159,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 14,
          'b1': 0,
          'b2': 0,
          'next': 163,
          'channel': 1,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 12,
          'data': {
            'value': 80,
            'channel': 1,
          },
          'next': 166,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 12,
          'data': {
            'value': 80,
            'channel': 1,
          },
          'next': 169,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 7,
            'value': 127,
            'channel': 1,
          },
          'next': 173,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 101,
            'value': 0,
            'channel': 1,
          },
          'next': 177,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 100,
            'value': 0,
            'channel': 1,
          },
          'next': 181,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 6,
            'value': 12,
            'channel': 1,
          },
          'next': 185,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 10,
            'value': 64,
            'channel': 1,
          },
          'next': 189,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 7,
            'value': 127,
            'channel': 1,
          },
          'next': 193,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 14,
          'b1': 0,
          'b2': 0,
          'next': 197,
          'channel': 1,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 12,
          'data': {
            'value': 80,
            'channel': 1,
          },
          'next': 200,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 12,
          'data': {
            'value': 80,
            'channel': 1,
          },
          'next': 203,
          'delta': 0,
          'time': 0,
        },
        {
          'type': 11,
          'data': {
            'control': 7,
            'value': 127,
            'channel': 1,
          },
          'next': 207,
          'delta': 0,
          'time': 0,
        },
        {
          'data': {
            'value': 71,
            'velocity': 127,
            'channel': 1,
          },
          'next': 211,
          'type': 9,
          'delta': 0,
          'time': 0,
        },
        {
          'data': {
            'value': 71,
            'velocity': 0,
            'channel': 1,
          },
          'next': 215,
          'type': 8,
          'delta': 12,
          'time': 12,
        },
        {
          'data': {
            'value': 83,
            'velocity': 127,
            'channel': 1,
          },
          'next': 219,
          'type': 9,
          'delta': 12,
          'time': 24,
        },
        {
          'data': {
            'value': 83,
            'velocity': 0,
            'channel': 1,
          },
          'next': 223,
          'type': 8,
          'delta': 12,
          'time': 36,
        },
        {
          'data': {
            'value': 78,
            'velocity': 127,
            'channel': 1,
          },
          'next': 227,
          'type': 9,
          'delta': 12,
          'time': 48,
        },
        {
          'data': {
            'value': 78,
            'velocity': 0,
            'channel': 1,
          },
          'next': 231,
          'type': 8,
          'delta': 12,
          'time': 60,
        },
        {
          'data': {
            'value': 75,
            'velocity': 127,
            'channel': 1,
          },
          'next': 235,
          'type': 9,
          'delta': 12,
          'time': 72,
        },
        {
          'data': {
            'value': 75,
            'velocity': 0,
            'channel': 1,
          },
          'next': 239,
          'type': 8,
          'delta': 12,
          'time': 84,
        },
        {
          'data': {
            'value': 83,
            'velocity': 127,
            'channel': 1,
          },
          'next': 243,
          'type': 9,
          'delta': 12,
          'time': 96,
        },
        {
          'data': {
            'value': 83,
            'velocity': 0,
            'channel': 1,
          },
          'next': 247,
          'type': 8,
          'delta': 12,
          'time': 108,
        },
        {
          'data': {
            'value': 78,
            'velocity': 127,
            'channel': 1,
          },
          'next': 251,
          'type': 9,
          'delta': 0,
          'time': 108,
        },
        {
          'data': {
            'value': 78,
            'velocity': 0,
            'channel': 1,
          },
          'next': 255,
          'type': 8,
          'delta': 12,
          'time': 120,
        },
        {
          'data': {
            'value': 75,
            'velocity': 127,
            'channel': 1,
          },
          'next': 259,
          'type': 9,
          'delta': 24,
          'time': 144,
        },
        {
          'data': {
            'value': 75,
            'velocity': 0,
            'channel': 1,
          },
          'next': 263,
          'type': 8,
          'delta': 36,
          'time': 180,
        },
        {
          'data': {
            'value': 72,
            'velocity': 127,
            'channel': 1,
          },
          'next': 267,
          'type': 9,
          'delta': 12,
          'time': 192,
        },
        {
          'data': {
            'value': 72,
            'velocity': 0,
            'channel': 1,
          },
          'next': 271,
          'type': 8,
          'delta': 12,
          'time': 204,
        },
        {
          'data': {
            'value': 84,
            'velocity': 127,
            'channel': 1,
          },
          'next': 275,
          'type': 9,
          'delta': 12,
          'time': 216,
        },
        {
          'data': {
            'value': 84,
            'velocity': 0,
            'channel': 1,
          },
          'next': 279,
          'type': 8,
          'delta': 12,
          'time': 228,
        },
        {
          'data': {
            'value': 79,
            'velocity': 127,
            'channel': 1,
          },
          'next': 283,
          'type': 9,
          'delta': 12,
          'time': 240,
        },
        {
          'data': {
            'value': 79,
            'velocity': 0,
            'channel': 1,
          },
          'next': 287,
          'type': 8,
          'delta': 12,
          'time': 252,
        },
        {
          'data': {
            'value': 76,
            'velocity': 127,
            'channel': 1,
          },
          'next': 291,
          'type': 9,
          'delta': 12,
          'time': 264,
        },
        {
          'data': {
            'value': 76,
            'velocity': 0,
            'channel': 1,
          },
          'next': 295,
          'type': 8,
          'delta': 12,
          'time': 276,
        },
        {
          'data': {
            'value': 84,
            'velocity': 127,
            'channel': 1,
          },
          'next': 299,
          'type': 9,
          'delta': 12,
          'time': 288,
        },
        {
          'data': {
            'value': 84,
            'velocity': 0,
            'channel': 1,
          },
          'next': 303,
          'type': 8,
          'delta': 12,
          'time': 300,
        },
        {
          'data': {
            'value': 79,
            'velocity': 127,
            'channel': 1,
          },
          'next': 307,
          'type': 9,
          'delta': 0,
          'time': 300,
        },
        {
          'data': {
            'value': 79,
            'velocity': 0,
            'channel': 1,
          },
          'next': 311,
          'type': 8,
          'delta': 12,
          'time': 312,
        },
        {
          'data': {
            'value': 76,
            'velocity': 127,
            'channel': 1,
          },
          'next': 315,
          'type': 9,
          'delta': 24,
          'time': 336,
        },
        {
          'data': {
            'value': 76,
            'velocity': 0,
            'channel': 1,
          },
          'next': 319,
          'type': 8,
          'delta': 36,
          'time': 372,
        },
        {
          'data': {
            'value': 71,
            'velocity': 127,
            'channel': 1,
          },
          'next': 323,
          'type': 9,
          'delta': 12,
          'time': 384,
        },
        {
          'data': {
            'value': 71,
            'velocity': 0,
            'channel': 1,
          },
          'next': 327,
          'type': 8,
          'delta': 12,
          'time': 396,
        },
        {
          'data': {
            'value': 83,
            'velocity': 127,
            'channel': 1,
          },
          'next': 331,
          'type': 9,
          'delta': 12,
          'time': 408,
        },
        {
          'data': {
            'value': 83,
            'velocity': 0,
            'channel': 1,
          },
          'next': 335,
          'type': 8,
          'delta': 12,
          'time': 420,
        },
        {
          'data': {
            'value': 78,
            'velocity': 127,
            'channel': 1,
          },
          'next': 339,
          'type': 9,
          'delta': 12,
          'time': 432,
        },
        {
          'data': {
            'value': 78,
            'velocity': 0,
            'channel': 1,
          },
          'next': 343,
          'type': 8,
          'delta': 12,
          'time': 444,
        },
        {
          'data': {
            'value': 75,
            'velocity': 127,
            'channel': 1,
          },
          'next': 347,
          'type': 9,
          'delta': 12,
          'time': 456,
        },
        {
          'data': {
            'value': 75,
            'velocity': 0,
            'channel': 1,
          },
          'next': 351,
          'type': 8,
          'delta': 12,
          'time': 468,
        },
        {
          'data': {
            'value': 83,
            'velocity': 127,
            'channel': 1,
          },
          'next': 355,
          'type': 9,
          'delta': 12,
          'time': 480,
        },
        {
          'data': {
            'value': 83,
            'velocity': 0,
            'channel': 1,
          },
          'next': 359,
          'type': 8,
          'delta': 12,
          'time': 492,
        },
        {
          'data': {
            'value': 78,
            'velocity': 127,
            'channel': 1,
          },
          'next': 363,
          'type': 9,
          'delta': 0,
          'time': 492,
        },
        {
          'data': {
            'value': 78,
            'velocity': 0,
            'channel': 1,
          },
          'next': 367,
          'type': 8,
          'delta': 12,
          'time': 504,
        },
        {
          'data': {
            'value': 75,
            'velocity': 127,
            'channel': 1,
          },
          'next': 371,
          'type': 9,
          'delta': 24,
          'time': 528,
        },
        {
          'data': {
            'value': 75,
            'velocity': 0,
            'channel': 1,
          },
          'next': 375,
          'type': 8,
          'delta': 36,
          'time': 564,
        },
        {
          'data': {
            'value': 75,
            'velocity': 127,
            'channel': 1,
          },
          'next': 379,
          'type': 9,
          'delta': 12,
          'time': 576,
        },
        {
          'data': {
            'value': 75,
            'velocity': 0,
            'channel': 1,
          },
          'next': 383,
          'type': 8,
          'delta': 12,
          'time': 588,
        },
        {
          'data': {
            'value': 76,
            'velocity': 127,
            'channel': 1,
          },
          'next': 387,
          'type': 9,
          'delta': 0,
          'time': 588,
        },
        {
          'data': {
            'value': 76,
            'velocity': 0,
            'channel': 1,
          },
          'next': 391,
          'type': 8,
          'delta': 12,
          'time': 600,
        },
        {
          'data': {
            'value': 77,
            'velocity': 127,
            'channel': 1,
          },
          'next': 395,
          'type': 9,
          'delta': 0,
          'time': 600,
        },
        {
          'data': {
            'value': 77,
            'velocity': 0,
            'channel': 1,
          },
          'next': 399,
          'type': 8,
          'delta': 12,
          'time': 612,
        },
        {
          'data': {
            'value': 77,
            'velocity': 127,
            'channel': 1,
          },
          'next': 403,
          'type': 9,
          'delta': 12,
          'time': 624,
        },
        {
          'data': {
            'value': 77,
            'velocity': 0,
            'channel': 1,
          },
          'next': 407,
          'type': 8,
          'delta': 12,
          'time': 636,
        },
        {
          'data': {
            'value': 78,
            'velocity': 127,
            'channel': 1,
          },
          'next': 411,
          'type': 9,
          'delta': 0,
          'time': 636,
        },
        {
          'data': {
            'value': 78,
            'velocity': 0,
            'channel': 1,
          },
          'next': 415,
          'type': 8,
          'delta': 12,
          'time': 648,
        },
        {
          'data': {
            'value': 79,
            'velocity': 127,
            'channel': 1,
          },
          'next': 419,
          'type': 9,
          'delta': 0,
          'time': 648,
        },
        {
          'data': {
            'value': 79,
            'velocity': 0,
            'channel': 1,
          },
          'next': 423,
          'type': 8,
          'delta': 12,
          'time': 660,
        },
        {
          'data': {
            'value': 79,
            'velocity': 127,
            'channel': 1,
          },
          'next': 427,
          'type': 9,
          'delta': 12,
          'time': 672,
        },
        {
          'data': {
            'value': 79,
            'velocity': 0,
            'channel': 1,
          },
          'next': 431,
          'type': 8,
          'delta': 12,
          'time': 684,
        },
        {
          'data': {
            'value': 80,
            'velocity': 127,
            'channel': 1,
          },
          'next': 435,
          'type': 9,
          'delta': 0,
          'time': 684,
        },
        {
          'data': {
            'value': 80,
            'velocity': 0,
            'channel': 1,
          },
          'next': 439,
          'type': 8,
          'delta': 12,
          'time': 696,
        },
        {
          'data': {
            'value': 81,
            'velocity': 127,
            'channel': 1,
          },
          'next': 443,
          'type': 9,
          'delta': 0,
          'time': 696,
        },
        {
          'data': {
            'value': 81,
            'velocity': 0,
            'channel': 1,
          },
          'next': 447,
          'type': 8,
          'delta': 12,
          'time': 708,
        },
        {
          'data': {
            'value': 83,
            'velocity': 127,
            'channel': 1,
          },
          'next': 451,
          'type': 9,
          'delta': 12,
          'time': 720,
        },
        {
          'data': {
            'value': 83,
            'velocity': 0,
            'channel': 1,
          },
          'next': 455,
          'type': 8,
          'delta': 24,
          'time': 744,
        },
        {
          'type': 11,
          'data': {
            'control': 101,
            'value': 0,
            'channel': 1,
          },
          'next': 459,
          'delta': 24,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 100,
            'value': 0,
            'channel': 1,
          },
          'next': 463,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 6,
            'value': 12,
            'channel': 1,
          },
          'next': 467,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 10,
            'value': 64,
            'channel': 1,
          },
          'next': 471,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 7,
            'value': 127,
            'channel': 1,
          },
          'next': 475,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 14,
          'b1': 0,
          'b2': 0,
          'next': 479,
          'channel': 1,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 12,
          'data': {
            'value': 80,
            'channel': 1,
          },
          'next': 482,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 101,
            'value': 0,
            'channel': 1,
          },
          'next': 486,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 100,
            'value': 0,
            'channel': 1,
          },
          'next': 490,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 6,
            'value': 12,
            'channel': 1,
          },
          'next': 494,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 10,
            'value': 64,
            'channel': 1,
          },
          'next': 498,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 7,
            'value': 127,
            'channel': 1,
          },
          'next': 502,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 14,
          'b1': 0,
          'b2': 0,
          'next': 506,
          'channel': 1,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 12,
          'data': {
            'value': 80,
            'channel': 1,
          },
          'next': 509,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 101,
            'value': 0,
            'channel': 1,
          },
          'next': 513,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 100,
            'value': 0,
            'channel': 1,
          },
          'next': 517,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 6,
            'value': 12,
            'channel': 1,
          },
          'next': 521,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 10,
            'value': 64,
            'channel': 1,
          },
          'next': 525,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 11,
          'data': {
            'control': 7,
            'value': 127,
            'channel': 1,
          },
          'next': 529,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 14,
          'b1': 0,
          'b2': 0,
          'next': 533,
          'channel': 1,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 12,
          'data': {
            'value': 80,
            'channel': 1,
          },
          'next': 536,
          'delta': 0,
          'time': 768,
        },
        {
          'type': 47,
          'next': 540,
          'delta': 0,
          'time': 768,
        },
      ],
      'length': 465,
    },
  ],
}
